# Generated by Django 4.2.4 on 2023-08-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_formed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_database.team')),
            ],
        ),
    ]
