# Generated by Django 4.2.4 on 2023-08-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserGroups",
            fields=[
                ("group_id", models.IntegerField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserPermissions",
            fields=[
                (
                    "permissions_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("persmission_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_joined", models.DateField()),
                ("email_address", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=1000)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.usergroups",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usergroups",
            name="permissions_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.userpermissions"
            ),
        ),
        migrations.CreateModel(
            name="Tickets",
            fields=[
                ("ticket_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ticket_details", models.CharField(max_length=100)),
                ("ticket_description", models.CharField(max_length=2000)),
                (
                    "assignee_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
    ]
