# Generated by Django 4.2.4 on 2023-08-24 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_alter_tickets_ticket_id_alter_usergroups_group_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("status_description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("ticket_title", models.CharField(max_length=100)),
                ("ticket_info", models.CharField(max_length=2000)),
                ("date_reported", models.DateField()),
                ("date_due", models.DateField()),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "type_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("type_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="usergroups",
            name="permissions_id",
        ),
        migrations.RemoveField(
            model_name="users",
            name="group_id",
        ),
        migrations.DeleteModel(
            name="Tickets",
        ),
        migrations.DeleteModel(
            name="UserGroups",
        ),
        migrations.DeleteModel(
            name="UserPermissions",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.tickettype"
            ),
        ),
    ]
