# Generated by Django 4.2.4 on 2023-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_status_ticket_tickettype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="status_id",
        ),
        migrations.AddField(
            model_name="status",
            name="status_name",
            field=models.CharField(
                default="test", max_length=20, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="status",
            name="status_description",
            field=models.CharField(max_length=100),
        ),
    ]
