# Generated by Django 4.2.4 on 2023-08-28 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0004_remove_status_status_id_status_status_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status_description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="date_due",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.status",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_info",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tickettype",
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="type_description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
