# Generated by Django 4.2.4 on 2023-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_status_status_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="date_due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
