# Generated by Django 4.2.4 on 2023-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_ticket_assignee_alter_ticket_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="type_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
